### ISSUE TITLE
GIS.lab Web: Does not work under Chromium Web Browser 

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gislab-web#27]
Using Chromium Web Browser after entering URL to launch GIS.lab Web, there is only menu buttons and white background, see figure below:

![gislab-web-chromium](https://cloud.githubusercontent.com/assets/13394357/13198694/f1d53a2a-d80f-11e5-8ed7-38cedb844ebb.png)

**Comment by imincik** [comment]
@lfurtkevicova , would you please provide some error messages from Django server and web browser console (web developer tools) ?

**Comment by marcel-dancak** [comment]
This usually happens when you are running application on several web browsers at the same time. It least in my case, it hangs on the login request. Sometimes it happens, sometimes it doesn't. Sometimes restart of the development server helps, and sometimes more restarts are required...

I would rather wait for a new login/logout implementation which is planned for the next week. It should be easier to test and investigate it more deeply.

**Comment by lfurtkevicova** [comment]
It seems that the problem is solved with current master, many thanks! Closing, feel free to re-open if needed.
